### ISSUE TITLE
Locked smartphone does't tracking 

### ISSUE THREAD

**Issue by ghost** [ruz76/android_patrac#9]
Steps to reproduce:
1. Connect to the server by "Pripojit"
2. Start movement and observe if app tracking location, if it's working correctly continue to next step. 
3. Lock the phone 
4. After 5 or 10 minutes of movement check if number of sent locations are similar than tracked locations
Actual result: Number of sent locations are around 100 , Number of tracked locations are 300 
Expected result: App has no reason why stop sending locations to server during movement

**Comment by ruz76** [comment]
I do not think that the problem is in lock of the phone. I have tried it on Doogee with Android 8.0 and the sending of positions continues even when the phone is locked. The problem is when it lost the data connection. After that it is not able to continue. I think that the thread that is responsible for sending the location is down.

**Comment by ruz76** [comment]
We have to simulate this situation in debug mode to get the reason.

**Comment by ruz76** [comment]
The problem was in keeping two many requests in queue. It has been fixed to have just one request for one type of command in one time.
